
version: '1.0'

# Data source configuration (your DBT project)
sources:
  dbt:
    project_path: '.'
    auto_update_schemas: true
    compile_timeout: 120

# Target API configuration
targets:
  fastapi:
    # For GitHub repositories
    repo: 'my-org/my-api-repo'
    path: 'app/models.py'
    
    # Or for local files
    # local_path: '../my-api/models.py'

# Validation rules
validation:
  # What should cause validation to fail
  fail_on:
    - missing_tables
    - missing_required_columns
  
  # What should generate warnings
  warn_on:
    - type_mismatches
    - missing_optional_columns
  
  # What to report as info
  info_on:
    - extra_columns

# Output configuration
output:
  format: terminal  # terminal, json, github
  include_suggestions: true
  max_issues_displayed: 20